CREATE TABLE IF NOT EXISTS site_profile (
  id INT AUTO_INCREMENT PRIMARY KEY,
  address TEXT NULL,
  email VARCHAR(190) NULL,
  phone VARCHAR(40) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
