CREATE TABLE IF NOT EXISTS job_applications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  email VARCHAR(190) NOT NULL,
  linkedin_url VARCHAR(255) NOT NULL,
  portfolio_url VARCHAR(255) NULL,
  resume_path VARCHAR(255) NOT NULL,
  resume_original_name VARCHAR(255) NULL,
  resume_mime VARCHAR(100) NULL,
  resume_size INT NULL,
  status ENUM('RECEIVED','REVIEWING','SHORTLISTED','REJECTED','HIRED') NOT NULL DEFAULT 'RECEIVED',
  applied_at DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
